@echo off
setlocal EnableExtensions
title DSH diagnostics collector

set "HERE=%~dp0"
set "OUT=%USERPROFILE%\Desktop\DSH-diagnostics"

if exist "%OUT%" rd /s /q "%OUT%" >nul 2>&1
mkdir "%OUT%" >nul 2>&1
if not exist "%OUT%" (
  echo [ERROR] cannot create %OUT%
  pause
  exit /b 1
)

echo Collecting diagnostic information ...
echo.

rem ---- 1. bootstrap logs ----
copy /y "%TEMP%\DSH-install-boot.log"   "%OUT%\" >nul 2>&1
copy /y "%TEMP%\DSH-install-output.log" "%OUT%\" >nul 2>&1
copy /y "%USERPROFILE%\Desktop\DSH-install-output.txt" "%OUT%\console-mode-output.txt" >nul 2>&1

rem ---- 2. the REAL installer log (this is where the GUI error lands) ----
if exist "%LOCALAPPDATA%\DSH-Installer" (
  xcopy /y /q "%LOCALAPPDATA%\DSH-Installer\*.log" "%OUT%\" >nul 2>&1
  xcopy /y /q /s "%LOCALAPPDATA%\DSH-Installer\*" "%OUT%\DSH-Installer-folder\" >nul 2>&1
)

rem ---- 3. environment ----
> "%OUT%\01-environment.txt" echo ==== when ====
>>"%OUT%\01-environment.txt" echo %date% %time%
>>"%OUT%\01-environment.txt" echo ==== machine ====
>>"%OUT%\01-environment.txt" echo COMPUTERNAME=%COMPUTERNAME%
>>"%OUT%\01-environment.txt" echo USERNAME=%USERNAME%
>>"%OUT%\01-environment.txt" echo ARCH=%PROCESSOR_ARCHITECTURE%
>>"%OUT%\01-environment.txt" ver
>>"%OUT%\01-environment.txt" echo ==== installer folder ====
>>"%OUT%\01-environment.txt" echo %HERE%
>>"%OUT%\01-environment.txt" dir /b "%HERE%"
>>"%OUT%\01-environment.txt" echo.
>>"%OUT%\01-environment.txt" echo NOTE: if the path above contains ".zip" you ran it
>>"%OUT%\01-environment.txt" echo       from inside the archive - that always fails.

set "PSEXE=%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe"
if not exist "%PSEXE%" set "PSEXE=powershell.exe"

rem ---- 4. THE KEY TEST (passed as base64 so cmd cannot mangle it) ----
echo Running WPF / .NET test ...
"%PSEXE%" -NoProfile -STA -EncodedCommand CgAkAEUAcgByAG8AcgBBAGMAdABpAG8AbgBQAHIAZQBmAGUAcgBlAG4AYwBlACAAPQAgACcAQwBvAG4AdABpAG4AdQBlACcACgBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACcAPQA9AD0APQAgAFAAbwB3AGUAcgBTAGgAZQBsAGwAIAA9AD0APQA9ACcACgBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACQAUABTAFYAZQByAHMAaQBvAG4AVABhAGIAbABlAC4AUABTAFYAZQByAHMAaQBvAG4ALgBUAG8AUwB0AHIAaQBuAGcAKAApAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAoACcAQQBwAGEAcgB0AG0AZQBuAHQAIAA9ACAAJwAgACsAIABbAFMAeQBzAHQAZQBtAC4AVABoAHIAZQBhAGQAaQBuAGcALgBUAGgAcgBlAGEAZABdADoAOgBDAHUAcgByAGUAbgB0AFQAaAByAGUAYQBkAC4ARwBlAHQAQQBwAGEAcgB0AG0AZQBuAHQAUwB0AGEAdABlACgAKQApAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnACcACgBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACcAPQA9AD0APQAgAFcAUABGACAAYQBzAHMAZQBtAGIAbABpAGUAcwAgAD0APQA9AD0AJwAKAHQAcgB5ACAAewAKACAAIAAgACAAQQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFAAcgBlAHMAZQBuAHQAYQB0AGkAbwBuAEYAcgBhAG0AZQB3AG8AcgBrACwAIABQAHIAZQBzAGUAbgB0AGEAdABpAG8AbgBDAG8AcgBlACwAIABXAGkAbgBkAG8AdwBzAEIAYQBzAGUALAAgAFMAeQBzAHQAZQBtAC4AWABhAG0AbAAKACAAIAAgACAAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnAFIARQBTAFUATABUADoAIABBAGQAZAAtAFQAeQBwAGUAIABPAEsAJwAKAH0AIABjAGEAdABjAGgAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACcAUgBFAFMAVQBMAFQAOgAgAEEAZABkAC0AVAB5AHAAZQAgAEYAQQBJAEwARQBEACcACgAgACAAIAAgAFcAcgBpAHQAZQAtAE8AdQB0AHAAdQB0ACAAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBUAG8AUwB0AHIAaQBuAGcAKAApAAoAfQAKAFcAcgBpAHQAZQAtAE8AdQB0AHAAdQB0ACAAJwAnAAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnAD0APQA9AD0AIABYAGEAbQBsAFIAZQBhAGQAZQByACAAPQA9AD0APQAnAAoAdAByAHkAIAB7AAoAIAAgACAAIAAkAHgAIAA9ACAAJwA8AFcAaQBuAGQAbwB3ACAAeABtAGwAbgBzAD0AIgBoAHQAdABwADoALwAvAHMAYwBoAGUAbQBhAHMALgBtAGkAYwByAG8AcwBvAGYAdAAuAGMAbwBtAC8AdwBpAG4AZgB4AC8AMgAwADAANgAvAHgAYQBtAGwALwBwAHIAZQBzAGUAbgB0AGEAdABpAG8AbgAiACAAVwBpAGQAdABoAD0AIgAxADAAMAAiACAASABlAGkAZwBoAHQAPQAiADEAMAAwACIALwA+ACcACgAgACAAIAAgACQAdwAgAD0AIABbAFcAaQBuAGQAbwB3AHMALgBNAGEAcgBrAHUAcAAuAFgAYQBtAGwAUgBlAGEAZABlAHIAXQA6ADoAUABhAHIAcwBlACgAJAB4ACkACgAgACAAIAAgAFcAcgBpAHQAZQAtAE8AdQB0AHAAdQB0ACAAJwBSAEUAUwBVAEwAVAA6ACAAWABhAG0AbABSAGUAYQBkAGUAcgAgAE8ASwAnAAoAIAAgACAAIABXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACgAJwBSAEUAUwBVAEwAVAA6ACAAdAB5AHAAZQAgAD0AIAAnACAAKwAgACQAdwAuAEcAZQB0AFQAeQBwAGUAKAApAC4ARgB1AGwAbABOAGEAbQBlACkACgB9ACAAYwBhAHQAYwBoACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnAFIARQBTAFUATABUADoAIABYAGEAbQBsAFIAZQBhAGQAZQByACAARgBBAEkATABFAEQAJwAKACAAIAAgACAAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAkAF8ALgBFAHgAYwBlAHAAdABpAG8AbgAuAFQAbwBTAHQAcgBpAG4AZwAoACkACgB9AAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnACcACgBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACcAPQA9AD0APQAgAC4ATgBFAFQAIABGAHIAYQBtAGUAdwBvAHIAawAgAD0APQA9AD0AJwAKAHQAcgB5ACAAewAKACAAIAAgACAAJABrACAAPQAgAEcAZQB0AC0ASQB0AGUAbQBQAHIAbwBwAGUAcgB0AHkAIAAnAEgASwBMAE0AOgBcAFMATwBGAFQAVwBBAFIARQBcAE0AaQBjAHIAbwBzAG8AZgB0AFwATgBFAFQAIABGAHIAYQBtAGUAdwBvAHIAawAgAFMAZQB0AHUAcABcAE4ARABQAFwAdgA0AFwARgB1AGwAbAAnACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAHQAbwBwAAoAIAAgACAAIABXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACgAJwBWAGUAcgBzAGkAbwBuACAAPQAgACcAIAArACAAJABrAC4AVgBlAHIAcwBpAG8AbgApAAoAIAAgACAAIABXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACgAJwBSAGUAbABlAGEAcwBlACAAPQAgACcAIAArACAAJABrAC4AUgBlAGwAZQBhAHMAZQApAAoAfQAgAGMAYQB0AGMAaAAgAHsACgAgACAAIAAgAFcAcgBpAHQAZQAtAE8AdQB0AHAAdQB0ACAAJwBjAGEAbgBuAG8AdAAgAHIAZQBhAGQAIAAuAE4ARQBUACAARgByAGEAbQBlAHcAbwByAGsAIAB2AGUAcgBzAGkAbwBuACcACgB9AAoAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnACcACgBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACcAPQA9AD0APQAgAGQAaQBzAHAAbABhAHkAIAAvACAAcwBlAHMAcwBpAG8AbgAgAD0APQA9AD0AJwAKAFcAcgBpAHQAZQAtAE8AdQB0AHAAdQB0ACAAKAAnAFMAZQBzAHMAaQBvAG4ASQBkACAAPQAgACcAIAArACAAKABHAGUAdAAtAFAAcgBvAGMAZQBzAHMAIAAtAEkAZAAgACQAUABJAEQAKQAuAFMAZQBzAHMAaQBvAG4ASQBkACkACgBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACgAJwBJAG4AdABlAHIAYQBjAHQAaQB2AGUAIAA9ACAAJwAgACsAIABbAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBVAHMAZQByAEkAbgB0AGUAcgBhAGMAdABpAHYAZQApAAoAdAByAHkAIAB7AAoAIAAgACAAIABBAGQAZAAtAFQAeQBwAGUAIAAtAEEAcwBzAGUAbQBiAGwAeQBOAGEAbQBlACAAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAAoAIAAgACAAIABXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACgAJwBTAGMAcgBlAGUAbgAgAD0AIAAnACAAKwAgAFsAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzAC4AUwB5AHMAdABlAG0ASQBuAGYAbwByAG0AYQB0AGkAbwBuAF0AOgA6AFYAaQByAHQAdQBhAGwAUwBjAHIAZQBlAG4ALgBUAG8AUwB0AHIAaQBuAGcAKAApACkACgB9ACAAYwBhAHQAYwBoACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAoACcAUwBjAHIAZQBlAG4AIABxAHUAZQByAHkAIABmAGEAaQBsAGUAZAA6ACAAJwAgACsAIAAkAF8ALgBFAHgAYwBlAHAAdABpAG8AbgAuAE0AZQBzAHMAYQBnAGUAKQAKAH0ACgA= > "%OUT%\02-wpf-and-dotnet.txt" 2>&1

rem ---- 5. execution policy ----
"%PSEXE%" -NoProfile -Command "Get-ExecutionPolicy -List | Out-String" > "%OUT%\03-execution-policy.txt" 2>&1

rem ---- 6. antivirus ----
"%PSEXE%" -NoProfile -Command "Get-CimInstance -Namespace root/SecurityCenter2 -ClassName AntiVirusProduct -ErrorAction SilentlyContinue | Select-Object displayName,productState | Format-List | Out-String" > "%OUT%\04-antivirus.txt" 2>&1

rem ---- 7. show result on screen ----
echo.
echo  ================================================================
echo   Result of the key test:
echo  ================================================================
type "%OUT%\02-wpf-and-dotnet.txt"
echo.
echo  ================================================================
echo   Everything was collected into:
echo     %OUT%
echo   Please ZIP that folder and send it to the developer.
echo  ================================================================
echo.
start "" "%OUT%"
pause
